title: 功夫熊猫的博客
email: your@email.com
description: >- 
  一个热爱技术的开发者的个人博客
baseurl: ""
url: "https://kanfu-panda.github.io"
github_username: kanfu-panda

# Gitalk 评论系统配置
gitalk:
  enable: true
  clientID: GITALK_CLIENT_ID     # 将从环境变量获取
  clientSecret: GITALK_CLIENT_SECRET # 将从环境变量获取
  repo: kanfu-panda.github.io    # 存储评论的 repo
  owner: kanfu-panda             # 您的 GitHub ID
  admin: ['kanfu-panda']         # 管理员名单
  id: location.pathname          # 页面唯一标识
  language: zh-CN               # 语言设置

# Build settings
markdown: kramdown

# Environment variables
env:
  GOOGLE_ANALYTICS_ID: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
baidu_analytics: xxxxxxxxxx # 替换为你的百度统计 ID

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 导航菜单
header_pages:
  - about.md
  - projects.md
