title: 功夫熊猫的博客
email: your@email.com
description: >- 
  一个热爱技术的开发者的个人博客
baseurl: ""
url: "https://kanfu-panda.github.io"
github_username: kanfu-panda

# Gitalk 评论系统配置
gitalk:
  enable: true
  clientID: "" # 将从 GitHub Actions 注入
  clientSecret: "" # 将从 GitHub Actions 注入
  repo: kanfu-panda.github.io    # 存储评论的 repo
  owner: kanfu-panda             # 您的 GitHub ID
  admin: ['kanfu-panda']         # 管理员名单
  id: location.pathname          # 页面唯一标识
  language: zh-CN               # 语言设置

# Analytics settings
google_analytics: "" # Will be set by GitHub Actions in production

# Build settings
markdown: kramdown

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 导航菜单
header_pages:
  - about.md
  - projects.md
