name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: 安装依赖
      run: |
        bundle install
      - name: 构建站点
      env:
        JEKYLL_ENV: production
      run: |
        echo "google_analytics: ${{ secrets.GOOGLE_ANALYTICS_ID }}" >> _config.yml
        bundle exec jekyll build
    
    - name: 部署到 GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
